title: Harrison Ritz
position: C.V. Starr Fellow
affiliation: Princeton University
affiliation_link: https://pni.princeton.edu/people/harrison-ritz
email: hritz (at) princeton.edu
email_address: hritz@princeton.edu
keywords: Harrison Ritz, Princeton, Brown, Computational Cognitive Neuroscience, Psychology, Cognitive Science, Cognitive Control, Attention, Planning, Cybernetics
google_scholar: https://scholar.google.com/citations?user=2MGy7zwAAAAJ
twitter: https://twitter.com/harrison_ritz
github_link: https://github.com/harrisonritz
orcid_link: https://orcid.org/0000-0003-3011-2946
avatar: ./assets/img/HarrisonRitz.jpg
google_analytics: UA-31678746-1
favicon: ./assets/img/HarrisonRitz.jpg
favicon_dark: ./assets/img/HarrisonRitz.jpg
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://harrisonritz.github.io
remote_theme: yaoyao-liu/minimal-light
